### ISSUE TITLE
Could not find any database drivers

### ISSUE THREAD

**Issue by probonopd** [appimage-packages/kexi#2]
Running kexi-git20170118-x86_64.AppImage on xubuntu-16.04-desktop-amd64.iso, creating a local database fails with "Could not find any database drivers".

**Comment by ScarlettGatelyMoore** [comment]
Was missing postgresql. But now I have hit
http://stackoverflow.com/questions/25193161/chfn-pam-system-error-intermittently-in-docker-hub-builds

Rebuilding docker image with fix.

**Comment by ScarlettGatelyMoore** [comment]
Fixed, please test.

**Comment by probonopd** [comment]
Seems solved, thanks!
