### ISSUE TITLE
PostgreSQL driver is missing

### ISSUE THREAD

**Issue by staniek** [appimage-packages/kexi#5]
PostgreSQL driver is missing in the binary kexi-git20170206-x86_64.AppImage or older.

To reproduce: 
1. Click Kexi button,  Click New...,  Click Server >,  Click Add...
2. Click the Engine combo box
3. Result: Only MySQL entry
4. Expected: MySQL and PostgreSQL entries are present

![pgsql](https://cloud.githubusercontent.com/assets/7920289/22842582/fa4c92be-efd5-11e6-91d0-6e2ba393aad7.png)

**Comment by ScarlettGatelyMoore** [comment]
Fixed.

**Comment by staniek** [comment]
Thanks Scarlett. Tested kexi-git20170314-x86_64.AppImage. 

Current issue on connection: `"/tmp/.mount_Cb4XFD/plugins/kdb3/kdb_postgresqldriver.so\"." "Cannot load        library /tmp/.mount_Cb4XFD/plugins/kdb3/kdb_postgresqldriver.so: (libkrb5.so.26: cannot open shared object file: No such file or directory)       "`

You can try to 'ldd kdb_postgresqldriver.so' to see what dependencies are required, possibly more than that.

The list for the binaries I built on openSUSE is:

> 	linux-vdso.so.1 (0x00007ffc18bfd000)
> 	libKDb3.so.3 => /home/jarek/dev/inst5/lib64/libKDb3.so.3 (0x00007fd3ff769000)
> 	libpq.so.5 => /usr/lib64/libpq.so.5 (0x00007fd3ff4e3000)
> 	libQt5Network.so.5 => /usr/lib64/libQt5Network.so.5 (0x00007fd3ff18c000)
> 	libQt5Widgets.so.5 => /usr/lib64/libQt5Widgets.so.5 (0x00007fd3fe919000)
> 	libQt5Gui.so.5 => /usr/lib64/libQt5Gui.so.5 (0x00007fd3fe1c3000)
> 	libKF5CoreAddons.so.5 => /usr/lib64/libKF5CoreAddons.so.5 (0x00007fd3fdf30000)
> 	libQt5Core.so.5 => /usr/lib64/libQt5Core.so.5 (0x00007fd3fd871000)
> 	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fd3fd4e7000)
> 	libm.so.6 => /lib64/libm.so.6 (0x00007fd3fd1ea000)
> 	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fd3fcfd3000)
> 	libc.so.6 => /lib64/libc.so.6 (0x00007fd3fcc2f000)
> 	libQt5Xml.so.5 => /usr/lib64/libQt5Xml.so.5 (0x00007fd3fc9f2000)
> 	libicui18n.so.52.1 => /usr/lib64/libicui18n.so.52.1 (0x00007fd3fc5de000)
> 	libssl.so.1.0.0 => /lib64/libssl.so.1.0.0 (0x00007fd3fc371000)
> 	libcrypto.so.1.0.0 => /lib64/libcrypto.so.1.0.0 (0x00007fd3fbf17000)
> 	libgssapi_krb5.so.2 => /usr/lib64/libgssapi_krb5.so.2 (0x00007fd3fbcce000)
> 	libldap_r-2.4.so.2 => /usr/lib64/libldap_r-2.4.so.2 (0x00007fd3fba77000)
> 	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fd3fb85a000)
> 	libz.so.1 => /lib64/libz.so.1 (0x00007fd3fb644000)
> 	libgobject-2.0.so.0 => /usr/lib64/libgobject-2.0.so.0 (0x00007fd3fb3f2000)
> 	libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0 (0x00007fd3fb0e2000)
> 	libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007fd3fada4000)
> 	libpng16.so.16 => /usr/lib64/libpng16.so.16 (0x00007fd3fab66000)
> 	libharfbuzz.so.0 => /usr/lib64/libharfbuzz.so.0 (0x00007fd3fa8d6000)
> 	libGL.so.1 => /usr/lib64/libGL.so.1 (0x00007fd3fa66c000)
> 	libicuuc.so.52.1 => /usr/lib64/libicuuc.so.52.1 (0x00007fd3fa2ec000)
> 	libpcre16.so.0 => /usr/lib64/libpcre16.so.0 (0x00007fd3fa086000)
> 	libdl.so.2 => /lib64/libdl.so.2 (0x00007fd3f9e82000)
> 	librt.so.1 => /lib64/librt.so.1 (0x00007fd3f9c79000)
> 	/lib64/ld-linux-x86-64.so.2 (0x000055d148050000)
> 	libkrb5.so.3 => /usr/lib64/libkrb5.so.3 (0x00007fd3f99a2000)
> 	libk5crypto.so.3 => /usr/lib64/libk5crypto.so.3 (0x00007fd3f976f000)
> 	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007fd3f956b000)
> 	libkrb5support.so.0 => /usr/lib64/libkrb5support.so.0 (0x00007fd3f935e000)
> 	liblber-2.4.so.2 => /usr/lib64/liblber-2.4.so.2 (0x00007fd3f914e000)
> 	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fd3f8f37000)
> 	libsasl2.so.3 => /usr/lib64/libsasl2.so.3 (0x00007fd3f8d1a000)
> 	libffi.so.4 => /usr/lib64/libffi.so.4 (0x00007fd3f8b10000)
> 	libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007fd3f88a1000)
> 	libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007fd3f8681000)
> 	libfreetype.so.6 => /usr/lib64/libfreetype.so.6 (0x00007fd3f83e3000)
> 	libgraphite2.so.3 => /usr/lib64/libgraphite2.so.3 (0x00007fd3f81bb000)
> 	libexpat.so.1 => /usr/lib64/libexpat.so.1 (0x00007fd3f7f91000)
> 	libxcb-dri3.so.0 => /usr/lib64/libxcb-dri3.so.0 (0x00007fd3f7d8d000)
> 	libxcb-present.so.0 => /usr/lib64/libxcb-present.so.0 (0x00007fd3f7b8a000)
> 	libxcb-sync.so.1 => /usr/lib64/libxcb-sync.so.1 (0x00007fd3f7984000)
> 	libxshmfence.so.1 => /usr/lib64/libxshmfence.so.1 (0x00007fd3f7780000)
> 	libglapi.so.0 => /usr/lib64/libglapi.so.0 (0x00007fd3f7552000)
> 	libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007fd3f7340000)
> 	libXdamage.so.1 => /usr/lib64/libXdamage.so.1 (0x00007fd3f713c000)
> 	libXfixes.so.3 => /usr/lib64/libXfixes.so.3 (0x00007fd3f6f36000)
> 	libX11-xcb.so.1 => /usr/lib64/libX11-xcb.so.1 (0x00007fd3f6d34000)
> 	libxcb-glx.so.0 => /usr/lib64/libxcb-glx.so.0 (0x00007fd3f6b1b000)
> 	libxcb-dri2.so.0 => /usr/lib64/libxcb-dri2.so.0 (0x00007fd3f6916000)
> 	libXxf86vm.so.1 => /usr/lib64/libXxf86vm.so.1 (0x00007fd3f6710000)
> 	libdrm.so.2 => /usr/lib64/libdrm.so.2 (0x00007fd3f6500000)
> 	libicudata.so.52.1 => /usr/lib64/libicudata.so.52.1 (0x00007fd3f62ff000)
> 	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007fd3f60fa000)
> 	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fd3f5ed4000)
> 	libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007fd3f5ccf000)
> 	libbz2.so.1 => /usr/lib64/libbz2.so.1 (0x00007fd3f5ac0000)

**Comment by ScarlettGatelyMoore** [comment]
Will need testing after next build :)

functions.sh tools blacklist removes this, @probono this seems to affect many of my appimages.

**Comment by staniek** [comment]
Since a new build appeared [here](https://s3-eu-central-1.amazonaws.com/ds9-apps/kexi-stable-master-appimage/kexi-latest-x86_64.AppImage), I tested it. I got this error when I clicked "Test connection" button in the "Add a new connection" dialog

> Could not load database driver's plugin file "/tmp/.mount_gaDQlG/plugins/kdb3/kdb_postgresqldriver.so". 
> Message from server: Cannot load library /tmp/.mount_gaDQlG/plugins/kdb3/kdb_postgresqldriver.so: (libhcrypto.so.4: cannot open shared object file: No such file or directory)

![image](https://cloud.githubusercontent.com/assets/7920289/25558745/3aabf98c-2d2d-11e7-91ee-2f396e0d9f87.png)
