### ISSUE TITLE
Add "Latest" appimage filename alias

### ISSUE THREAD

**Issue by staniek** [appimage-packages/kexi#6]
Hello,
Thanks for the regular builds, they work great. 
My concern is, would it be possible to autmatically add a "Latest" appimage filename alias (symlink) to the newest appimage at https://s3-eu-central-1.amazonaws.com/ds9-apps/index.html#!/kexi-master-appimage%2F? 

e.g. a link from kexi-git20170308-x86_64.AppImage -> kexi-latest-x86_64.AppImage

That would be cool because the URL would be constant.

**Comment by ScarlettGatelyMoore** [comment]
seems s3 does not support symlinks. I can however create 2 appimages, the dated one and a latest one which would be over written each upload. THis should achieve our desired results.

**Comment by staniek** [comment]
Ah that's right. A copy is fine too, thanks.

**Comment by ScarlettGatelyMoore** [comment]
This is now complete:
https://s3-eu-central-1.amazonaws.com/ds9-apps/kexi-master-appimage/kexi-latest-x86_64.AppImage

There is also a link in the website section on github. This was a fabulous idea :) using it for the rest of the appimages.
Thanks!

**Comment by staniek** [comment]
Cool, I was able to make https://community.kde.org/Kexi/Snapshots much easier to use.
